### ISSUE TITLE
Start console in active workspace or project folder

### ISSUE THREAD

**Issue by Gert-dev** [npezza93/archipelago-atom#10]
Hello

It would be neat if, when spawning a console in an Atom window that doesn't have one yet, the (first) project folder would be the working directory for the terminal. I believe both `platformio-ide-terminal` as well as `Termrk` support this as well.

## Expected Behavior
The working directory of the terminal is that of the active project.

## Actual Behavior
The working directory is always the default working directory, i.e. the home folder on Linux.

## Steps to Reproduce
Open a new console.

## OS Used
- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Thanks for the suggestion, @Gert-dev!
