### ISSUE TITLE
Also focus when toggling terminal

### ISSUE THREAD

**Issue by Gert-dev** [npezza93/archipelago-atom#11]
First off, thanks for adding toggling! I'm already liking this terminal very much because you took the effort to use an actual Atom dock, which plays nice with other docks.

A minor detail is that the terminal isn't actually focused when toggling it on. In other words, you can't immediately start typing after toggling it, you need to click inside the terminal at least once first.

## Expected Behavior
After toggling the terminal open, focus is immediately placed inside terminal so you can start typing.

## Actual Behavior
Focus is always set to another element (not sure which), even if focus was there before.

## Steps to Reproduce
Toggle the terminal to open it.

## OS Used
- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Yea I've noticed that too and it is driving me crazy 😆. This is definitely on my list of things to fix!
