### ISSUE TITLE
Weird background color changes on Linux

### ISSUE THREAD

**Issue by Gert-dev** [npezza93/archipelago-atom#12]
I'm experiencing a strange background color issue. Not sure if this is somehow related to my theme (I'm using nebula-ui) or some other setting. I've attached a gif below.

## Expected Behavior
The background color of the terminal and the window are the colors that is set in the settings screen.

## Actual Behavior
The background color of the terminal works, but the background color of the window seems to be its default color and sometimes partially transitions to the desired color. This happens on mouse hover, for example.

![example](https://user-images.githubusercontent.com/24809863/34681308-c2754fae-f49b-11e7-8586-907e3c989994.gif)

## OS Used
- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by Gert-dev** [comment]
This is now fixed, thanks! The right part of the terminal is now black as is set in the settings panel and doesn't crossfade on hover anymore. 

If you look to the left on the screenshot, there is also some part of the dock that is not colored in the background color from the settings. This seems to be part of the `archipelago-pane` element, which seems to have a separate background-color set.

I could fix it by changing the `background` property of the `.archipelago archipelago-pane` selector to the color set in the settings by inspecting it in the developer tools.

**Comment by npezza93** [comment]
Yea in the settings for the package under "Theme" there is "Window Background" that's what controls the background for that particular PaneItem. The terminal has its own background color(Theme -> Theme Background) which is separate from the entire pane(Theme -> Window Background). I think I'm going to merge these together so they are both the same. I can't think of a reason you'd want the pane background different from the terminal's background.

**Comment by Gert-dev** [comment]
Thanks for the response. I noticed those settings and have both `Theme Background` as well as `Window Background` set to black. This seems to work everywhere, except for a tiny compartment to the left and a somewhat thick border (both visible in the screenshot). Restarting seems to have no effect, but changing the `background` for the `.archipelago archipelago-pane` selector in the developer tools works.

Perhaps the color is being reset or overwritten after being applied from the settings?

**Comment by npezza93** [comment]
Should be resolved in 0.9.0.
