### ISSUE TITLE
Cursor spazzing a bit

### ISSUE THREAD

**Issue by Gert-dev** [npezza93/archipelago-atom#13]
I noticed the cursor seems to be spazzing a bit. This _may_ or may not be caused by one of the last updates, I'm not sure if this was here before but may simply not have noticed it earlier.

Screenshot of the behavior:

![spazzing cursor](https://user-images.githubusercontent.com/24809863/34740211-e47848fc-f57e-11e7-99c6-4c9aef3b02d8.gif)

In the screenshot the cursor just seems to be flickering at somewhat random intervals - because the gif has a limited amount of frames per second - but in reality it is flickering at lightning fast speeds sometimes.

I noticed that this doesn't seem to happen until after you toggle the terminal a few times or you submit some commands. Perhaps a timeout that is animating the cursor that is being registered more than once on each toggle?

## Expected Behavior
Cursor doesn't spazz.

## Actual Behavior
Cursor seems to spazz.

## Steps to Reproduce
Open the terminal and give it focus. Toggle it a few times or enter some commands.

## OS Used
- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Should be resolved in 0.9.0.
