### ISSUE TITLE
Passwords do not seem to be retrieved from system keyring?

### ISSUE THREAD

**Issue by Gert-dev** [npezza93/archipelago-atom#14]
It seems that, whenever I perform a `git pull`, I need to enter my SSH private key password again. This happens even though it is already unlocked in my system's keyring (gnome-keyring), which also works properly with a native platform terminal. Is there perhaps some kind of additional activation I need to do to get this working inside archipelago?

If useful, this did work with other Atom terminals, so it seems to at least be possible in Atom, though I'm not sure what is necessary to achieve it.

## Expected Behavior
Password is not requested when already unlocked via the keyring.

## Actual Behavior
Password is always requested, even if it was previously successfully entered.

## Steps to Reproduce
Use a command that requires unlocking via the keychain, such as a `git pull` for a Git repository that is using SSH public key authentication.

## OS Used
- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Thanks, I noticed this too. I'll get a fix out for this.
