### ISSUE TITLE
Finial Line is cut off

### ISSUE THREAD

**Issue by ncino-cpezza** [npezza93/archipelago-atom#15]
## Expected Behavior
Not to be cut off

## Actual Behavior
Last line is bring cut off

## Steps to Reproduce
As seen in the image below the last line in the bottom window the last line is cut off and it is scrolled up as high as it allows

<img width="1153" alt="screen shot 2018-01-28 at 7 09 44 am" src="https://user-images.githubusercontent.com/17617672/35481880-7dca7bb8-03fa-11e8-98b2-3974514e971f.png">

## OS Used
- [ ] Linux
- [x] Mac
- [ ] Windows

**Comment by npezza93** [comment]
I think this is due to how we are setting the margin on the terminal. In xterm 3.1 they added a way to add a padding to the element. I think #16 should fix this.

**Comment by npezza93** [comment]
Updated to package to use xterm 3.1. Let me know if this stops happening now
