### ISSUE TITLE
Uncaught TypeError: Cannot read property 'click' of null

### ISSUE THREAD

**Issue by ghost** [npezza93/archipelago-atom#17]
[Enter steps to reproduce:]

1. Open the closed terminal via the shortcut and type something.

This doesn't _always_ happen, but about 50% of the time. Sometimes I can open the terminal just fine and once that works, everything continues working. It usually happens just after opening a new project window and trying to open a new terminal for the first time there. Once it happens, you also can't type anything; the error will keep popping up.

I believe this is a regression in v0.12.0 or v0.12.1, as it never happened before these releases.

**Atom**: 1.27.2 x64
**Electron**: 1.8.4
**OS**: linux 4.16.13
**Thrown From**: [archipelago](https://github.com/npezza93/archipelago-atom) package 0.12.1

### Stack Trace

Uncaught TypeError: Cannot read property 'click' of null

```
At /home/user/.atom/packages/archipelago/lib/session.coffee:85

TypeError: Cannot read property 'click' of null
    at Session.module.exports.Session.keybindingHandler (/packages/archipelago/lib/session.coffee:85:69)
    at Terminal._customKeyEventHandler (/packages/archipelago/lib/session.coffee:1:1)
    at Terminal._keyDown (/packages/archipelago/node_modules/xterm/lib/Terminal.js:908:49)
    at /packages/archipelago/node_modules/xterm/lib/Terminal.js:391:67)
```

### Commands

```
     -0:31.1.0 intentions:highlight (input.hidden-input)
     -0:31.1.0 core:copy (input.hidden-input)
     -0:18 intentions:highlight (input.hidden-input)
     -0:17.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:10.3.0 core:select-all (input.hidden-input)
     -0:10.1.0 core:backspace (input.hidden-input)
     -0:06.1.0 editor:consolidate-selections (input.hidden-input)
     -0:06.1.0 core:cancel (input.hidden-input)
     -0:05.9.0 intentions:highlight (input.hidden-input)
     -0:05.8.0 pane:show-next-item (input.hidden-input)
  2x -0:05.6.0 archipelago:toggle (input.hidden-input)
     -0:03.8.0 editor:consolidate-selections (input.hidden-input)
     -0:03.8.0 core:cancel (input.hidden-input)
     -0:02.1.0 intentions:highlight (input.hidden-input)
     -0:02.0 archipelago:toggle (input.hidden-input)
```

**Comment by npezza93** [comment]
Hey @tominventisbe! Thanks for pointing this out, I have released a patch that resolves the error.
