### ISSUE TITLE
Requires g++ to install on Linux

### ISSUE THREAD

**Issue by Gert-dev** [npezza93/archipelago-atom#8]
Hello

I wanted to mention that, at least on Linux, installing this package requires g++ or the build will fail. It might be interesting to mention that in the README somewhere.

## Expected Behavior
Perhaps a note in the readme?

## Actual Behavior
Installation fails when g++ or a C++ compiler is not installed.

## Steps to Reproduce
Install via Atom on Linux.

## OS Used
- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Thanks!
