### ISSUE TITLE
Ability to toggle console

### ISSUE THREAD

**Issue by Gert-dev** [npezza93/archipelago-atom#9]
Hello

Currently it's not possible to easily toggle the (dock showing the) console using a keybinding. The current keybinding for opening archipelago always seems to open a new console. `Termrk` as well as `platformio-ide-terminal` offer this functionality, although they do not use an actual Atom dock, AFAIK.

## Expected Behavior
A separate keybinding to show (and/or open) the console when it is closed and hide it when it is opened.

## Actual Behavior
A new console is always spawned.

## Steps to Reproduce
Open a new console and try to open another console.

## OS Used
- [X] Linux
- [ ] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Added in 0.7.0
